- hosts: all
  tasks:
    - name: stop container
      shell: docker container stop dockeransible
    - name: remove container
      shell: docker container rm dockeransible
    - name: docker image removal
      shell: docker image rm -f ghostiexd/jenkins-docker-ansible
    - name: create new container
      shell: docker run -itd --name dockeransible -p 9000:80 ghostiexd/jenkins-docker-ansible
  
